import { StateGraph, StateSchema, START, END, type GraphNode, type CompiledStateGraph } from "@langchain/langgraph"
import z from "zod";
import {  cohereModel, geminiModel, mistralAIModel } from "./model.ai.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})

function getStatusCode(err: unknown): number | undefined {
    if (typeof err !== "object" || err === null) return undefined;
    const e = err as Record<string, unknown>;
    if (typeof e.statusCode === "number") return e.statusCode;
    if (typeof e.status === "number") return e.status;
    // Some SDKs nest it: err.body / rawResponse.status
    const raw = e.rawResponse as { status?: number } | undefined;
    if (raw && typeof raw.status === "number") return raw.status;
    if (typeof e.code === "number") return e.code;
    if (typeof e.code === "string" && e.code === "1300") return 429; // Mistral rate_limited
    const msg = typeof e.message === "string" ? e.message : "";
    if (/status\s*:?\s*429|rate[_\s-]?limit/i.test(msg)) return 429;
    return undefined;
}

function isRateLimitError(err: unknown): boolean {
    return getStatusCode(err) === 429;
}

function sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

async function invokeWithRetry<T>(
    fn: () => Promise<T>,
    provider: string,
    maxRetries = 1,
): Promise<T> {
    let lastErr: unknown;
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
        try {
            return await fn();
        } catch (err) {
            lastErr = err;
            // Only retry rate limits / 5xx, not auth or bad-request errors.
            const status = getStatusCode(err);
            const retryable = status === 429 || (status !== undefined && status >= 500);
            if (!retryable || attempt === maxRetries) break;
            // Exponential backoff: 2s then 4s. Respects rate-limit headers.
            await sleep(2000 * (attempt + 1));
        }
    }
    throw withProviderContext(lastErr, provider);
}

function withProviderContext(err: unknown, provider: string): Error & { statusCode?: number; status?: number; provider?: string } {
    const status = getStatusCode(err);
    const baseMsg =
        err instanceof Error && err.message
            ? (err.message.split("\n")[0] ?? "").slice(0, 300)
            : String(err).slice(0, 300);
    const friendly =
        status === 429
            ? `${provider} rate limit exceeded (429). Quota is exhausted (limit-req-minute: 0 in headers). Wait ~60s, reduce request frequency, or check billing/quota in the ${provider} console.`
            : `${provider} request failed${status ? ` (status ${status})` : ""}: ${baseMsg}`;
    const wrapped = new Error(friendly) as Error & { statusCode?: number; status?: number; provider?: string };
    wrapped.cause = err;
    if (status !== undefined) {
        wrapped.statusCode = status;
        wrapped.status = status;
    }
    wrapped.provider = provider;
    return wrapped;
}


const solutionNode: GraphNode<typeof state> = async (state) => {

    // Retry once on 429 with backoff; don't hammer a rate-limited provider.
    // Promise.allSettled lets us report WHICH provider failed instead of a generic crash.
    const [mistralResult, cohereResult] = await Promise.allSettled([
        invokeWithRetry(() => mistralAIModel.invoke(state.problem), "Mistral"),
        invokeWithRetry(() => cohereModel.invoke(state.problem), "Cohere"),
    ])

    if (mistralResult.status === "rejected") {
        throw withProviderContext(mistralResult.reason, "Mistral");
    }
    if (cohereResult.status === "rejected") {
        throw withProviderContext(cohereResult.reason, "Cohere");
    }

    return {
        solution_1: mistralResult.value.text,
        solution_2: cohereResult.value.text,
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    const judge = createAgent({
        model: geminiModel,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })

    let judgeResponse;
    try {
        judgeResponse = await invokeWithRetry(
            () =>
                judge.invoke({
                    messages: [
                        new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `),
                    ],
                }),
            "Gemini (judge)",
        );
    } catch (err) {
        throw withProviderContext(err, "Gemini (judge)");
    }

    const structured = judgeResponse.structuredResponse;
    if (!structured) {
        throw new Error("Judge model returned no structured response. Try again.");
    }

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = structured

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }

}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default async function (problem: string) { 

    const result = await graph.invoke({
        problem: problem
    })

    return result

}